new
kabakmichal/team-project-modul2-gr1 pull request #19
Opened 2022-09-14 00:26 UTC by paliszoman

2022-09-14 03:54 UTC, kabakmichal requested changes
Do drobnych poprawek

2022-09-14 03:54 UTC, kabakmichal commented on src/index.js
> +    data.results;
Po returnie to się chyba nie wykonuje.

2022-09-14 03:54 UTC, kabakmichal commented on src/partials/page-footer.html
> +      >
Uciekło do następnej linii

2022-09-14 20:52 UTC, paliszoman commented on src/index.js
> +    data.results;
to zwraca tablicę do kolejnego .then

2022-09-15 15:50 UTC, kabakmichal approved these changes

2022-09-15 15:50 UTC, merged